/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_pitchblacknights_oxidizemc_OxidizeMC */

#ifndef _Included_io_github_pitchblacknights_oxidizemc_OxidizeMC
#define _Included_io_github_pitchblacknights_oxidizemc_OxidizeMC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_pitchblacknights_oxidizemc_OxidizeMC
 * Method:    returnTest
 * Signature: (Ljava/lang/Integer;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_github_pitchblacknights_oxidizemc_OxidizeMC_returnTest
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_github_pitchblacknights_oxidizemc_OxidizeMC
 * Method:    testLogString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_github_pitchblacknights_oxidizemc_OxidizeMC_testLogString
  (JNIEnv *, jclass, jstring);

/*
 * Class:     io_github_pitchblacknights_oxidizemc_OxidizeMC
 * Method:    testLogLevel
 * Signature: (Lorg/slf4j/event/Level;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_github_pitchblacknights_oxidizemc_OxidizeMC_testLogLevel
  (JNIEnv *, jclass, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
