[toolchain]
channel = "1.85.1"
targets = [
    "x86_64-pc-windows-msvc",
    "x86_64-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "aarch64-unknown-linux-gnu",
    "aarch64-pc-windows-msvc",
    "aarch64-apple-darwin"
]
components = ["clippy", "rustfmt"]


